language: c++

matrix:
  include:
    - env: CONF=""
      os: linux
      arch: amd64
      dist: bionic
      sudo: required
      compiler: gcc
      addons: &linuxaddons
        apt:
          sources: &sources
            - ubuntu-toolchain-r-test
          packages: &packages
            - libzmq3-dev
            - libzmq5
            - automake
            - libtool
            - vlc-data
            - libvlc-dev
            - libasound2
            - libasound2-dev
            - libjack-jackd2-dev
            - jackd2
            - libmagickwand-dev
            - g++-9

    - env: CONF="--enable-alsa"
      os: linux
      arch: amd64
      dist: bionic
      sudo: required
      compiler: gcc
      addons: *linuxaddons

    - env: CONF="--enable-jack"
      os: linux
      arch: amd64
      dist: bionic
      sudo: required
      compiler: gcc
      addons: *linuxaddons

    - env: CONF="--enable-vlc"
      os: linux
      arch: amd64
      dist: bionic
      sudo: required
      compiler: gcc
      addons: *linuxaddons

    - env: CONF="--enable-alsa --enable-jack --enable-vlc"
      os: linux
      arch: amd64
      dist: bionic
      sudo: required
      compiler: gcc
      addons: *linuxaddons

    - env: CONF="--enable-alsa --enable-jack --enable-vlc"
      os: linux
      arch: arm64
      dist: bionic
      sudo: required
      compiler: gcc
      addons: *linuxaddons

script:
  - |
    ./bootstrap
    CC=gcc-9 CXX=g++-9 ./configure $CONF
    make

