language: c++

matrix:
  include:
    - env: CONF=""
      os: osx
      osx_image: xcode11
      compiler: clang

    - env: CONF=""
      os: linux
      arch: amd64
      dist: bionic
      sudo: required
      compiler: gcc
      addons: &linuxaddons
        apt:
          sources: &sources
            - sourceline: 'ppa:ubuntu-toolchain-r/test'
          packages: &packages
            - libzmq3-dev
            - libzmq5
            - automake
            - libtool
            - vlc-data
            - libvlc-dev
            - vlc-plugin-base
            - libasound2
            - libasound2-dev
            - libjack-jackd2-dev
            - jackd2
            - libgstreamer1.0-dev
            - g++-9

    - env: CONF="--enable-alsa"
      os: linux
      arch: amd64
      dist: bionic
      sudo: required
      compiler: gcc
      addons: *linuxaddons

    - env: CONF="--enable-jack"
      os: linux
      arch: amd64
      dist: bionic
      sudo: required
      compiler: gcc
      addons: *linuxaddons

    - env: CONF="--enable-vlc"
      os: linux
      arch: amd64
      dist: bionic
      sudo: required
      compiler: gcc
      addons: *linuxaddons

    - env: CONF="--enable-gst"
      os: linux
      arch: amd64
      dist: bionic
      sudo: required
      compiler: gcc
      addons: *linuxaddons

    - env: CONF="--enable-alsa --enable-jack --enable-vlc --enable-gst"
      os: linux
      arch: amd64
      dist: bionic
      sudo: required
      compiler: gcc
      addons: *linuxaddons

    - env: CONF="--enable-alsa --enable-jack --enable-vlc --enable-gst"
      os: linux
      arch: arm64
      dist: bionic
      sudo: required
      compiler: gcc
      addons: *linuxaddons

before_install:
  - |
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
    brew update
    brew install automake || true
    brew install zeromq || true
    fi

script:
  - |
    ./bootstrap
    if [[ "$TRAVIS_OS_NAME" != "osx" ]]; then
    export CC=gcc-9
    export CXX=g++-9
    fi
    ./configure $CONF
    make

